/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package com.mycompany.poe_part1;

import java.util.ArrayList;
import javax.swing.*;

/**
 *
 * @author RC_Student_lab
public */
 class Task {
     //private declarations;
     private static String[] taskname ;
     private static int[] taskNumber;
     private static String[] description;
     static String[] developerDetails;
     private static int[] taskDuration;
     private static String[] taskID;
     private static String[] taskStatus;

 //passing the Show Report class in the Task class
     private ShowReport show = new ShowReport();
     
//check task Description
    public boolean checkTaskDescription(String description){
        return description.length()<50;
    }
    
    //Creating the task ID
    public String createTaskID(String taskname ,String developerDetails, int taskNumber){
        String firstTwoLetters=taskname.substring(0,2).toUpperCase();
        String lastThreeLetters=developerDetails.substring(developerDetails.length()-3).toUpperCase();
        return firstTwoLetters+":" + taskNumber + ":"+ lastThreeLetters;
    }
    
    //display task details
     public String printTaskDetails(int details){
         return "Task Status: " +taskStatus[details] + "\nDeveloper Details: " + developerDetails[details] + "\nTask Number: " + taskNumber[details] + "\nTask Name: " + taskname[details] + "\nTask Description: " + description[details] + "\nTask ID: " + taskID[details] + "\nDuration: " +taskDuration[details] ;
     }
      
     //return estimated hours
      public int returnTotalHours( int taskDuration) {
        return taskDuration;
      }
      
     //Add tasks method
      public void addTasks(){
           // Use an ArrayList to store tasks
        ArrayList<Task> taskList = new ArrayList<>();
        
        //Declarations
         String[] selection=new String[]{"To Do","Doing","Done"};
         int numTasks=0;
         
         //Prompt user for to enter as many tasks as they wish
          String input= JOptionPane.showInputDialog(null,"How many tasks do you wish to enter?");
         try{
             numTasks = Integer.parseInt(input);
          
             //loop the number of tasks
               for (int i = 0; i < numTasks; i++) {

            //Prompt the user to enter task name
            taskname = new String[numTasks];
            taskname[i] = JOptionPane.showInputDialog("Enter Task Name: " + (i + 1) );
            
            //Prompt the user to enter task number
            taskNumber= new int[numTasks];
            taskNumber[i]=i;
            
            //Prompt the user to enter task description
            description=new String[numTasks];
           do{
               description[i] = JOptionPane.showInputDialog("Enter Task Description:");
           
           
                //Check if the descrioption meets the requriements
            if(!checkTaskDescription(description[i])){
                JOptionPane.showMessageDialog(null, "Task Description is too long, try again.");
            }else{
                continue;
            }
           }while(description[i].length()>50);
           
           //Prompt the user to enter task developer details
           developerDetails = new String[numTasks];
           developerDetails[i] = JOptionPane.showInputDialog("Enter Developer Details:");
           
           //Prompt the user to enter task duration in hours
           taskDuration = new int [numTasks];
           taskDuration[i] = Integer.parseInt(JOptionPane.showInputDialog("Enter Task Duration (in hours):"));
           
           //Task ID should be autogenerated
           taskID= new String[numTasks];
           taskID[i]=createTaskID(taskname[i] ,developerDetails[i],i);
           JOptionPane.showMessageDialog(null,"Task ID:" + taskID[i]);
           
           //Display and question message for the Task 
           taskStatus= new String[numTasks];
           taskStatus[i]= (String)JOptionPane.showInputDialog(null,"Select Task Status:","Task Status:",JOptionPane.QUESTION_MESSAGE,null,selection,selection[2]);
               
          // Printing the details of the captured tasks
            JOptionPane.showMessageDialog(null,"Tasks successfully captured:\n" + printTaskDetails(i));
               }
               
         
      }catch(NumberFormatException e){
          JOptionPane.showMessageDialog(null,"Please try again");
          return;
                  
      }
      }
      
      //method for the show report 
       public void showReport() {
        while (true) {
           int option = Integer.parseInt(JOptionPane.showInputDialog("""
                                                                     Choose a report option:
                                                                     1.Display All the task
                                                                     2.Display task with Done status
                                                                     3.Display longest duration of tasks
                                                                     4.Search task by name
                                                                     5.Search task by developer name
                                                                     6.Delete tasks
                                                                     7.back""")); 
        switch (option) {
               case 1:
            // displays all the tasks captured
            JOptionPane.showMessageDialog(null,show.displayAllTasks());
            
                case 2:
            // displays all the Done tasks
            JOptionPane.showMessageDialog(null, show.displayStatusDone(developerDetails,taskname,taskDuration));
            
                case 3:
            //display the longest duration of tasks
            JOptionPane.showMessageDialog(null,show.longestDuration(developerDetails,taskname,taskDuration));
            
                case 4:
            // Search task by task name 
                    
            String searchname = JOptionPane.showInputDialog("Enter task name to search:");
           show.searchTaskname(taskname,searchname);
            
                case 5:
            // search task by developer names 
            String input=JOptionPane.showInputDialog("Enter developer name to search:");
            show.searchTaskByDeveloper(developerDetails,input);

                case 6:
            // Enable user to delete the capured tasks
           String deleteTaskname= JOptionPane.showInputDialog("Enter task name to delete:");
           show.deleteTask(taskname,deleteTaskname);
            
            default:
              JOptionPane.showMessageDialog(null,"Invalid option");
              break;
                 }
            }
        }
}
