/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package com.mycompany.poe_part1;

import java.util.ArrayList;
import javax.swing.*;

/**
 *
 * @author RC_Student_lab
public */
 class Task {
     //private declarations;
     private Task[] tasks;
     private static int numTasks=100;
     private static String[]taskname = new String[numTasks] ;
     private static int[] taskNumber= new int[numTasks] ;
     private static String[] description= new String[numTasks] ;
     static String[] developerDetails= new String[numTasks] ;
     private static int[] taskDuration= new int[numTasks] ;
     private static String[] taskID= new String[numTasks] ;
     private static String[] taskStatus= new String[numTasks] ;
     
//check task Description
    public boolean checkTaskDescription(String description){
        return description.length()<50;
    }
    
    //Creating the task ID
    public String createTaskID(String taskname ,String developerDetails, int taskNumber){
        String firstTwoLetters=taskname.substring(0,2).toUpperCase();
        String lastThreeLetters=developerDetails.substring(developerDetails.length()-3).toUpperCase();
        return firstTwoLetters+":" + taskNumber + ":"+ lastThreeLetters;
    }
    
    //display task details
     public String printTaskDetails(int details){
         return "Task Status: " +taskStatus[details] + "\nDeveloper Details: " + developerDetails[details] + "\nTask Number: " + taskNumber[details] + "\nTask Name: " + taskname[details] + "\nTask Description: " + description[details] + "\nTask ID: " + taskID[details] + "\nDuration: " +taskDuration[details] ;
     }
      
     //return estimated hours
      public int returnTotalHours( int taskDuration) {
        return taskDuration;
      }
      
     //Add tasks method
      public void addTasks(){
           // Use an ArrayList to store tasks
        ArrayList<Task> taskList = new ArrayList<>();
        
        //Declarations
         String[] selection=new String[]{"To Do","Doing","Done"};
         int numTasks=0;
         
         //Prompt user for to enter as many tasks as they wish
          String input= JOptionPane.showInputDialog(null,"How many tasks do you wish to enter?");
         try{
             numTasks = Integer.parseInt(input);
          
             //loop the number of tasks
               for (int i = 0; i < numTasks; i++) {

            //Prompt the user to enter task name
            taskname = new String[numTasks];
            taskname[i] = JOptionPane.showInputDialog("Enter Task Name: " + (i + 1) );
            
            //Prompt the user to enter task number
            taskNumber= new int[numTasks];
            taskNumber[i]=i;
            
            //Prompt the user to enter task description
            description=new String[numTasks];
           do{
               description[i] = JOptionPane.showInputDialog("Enter Task Description:");
           
           
                //Check if the descrioption meets the requriements
            if(!checkTaskDescription(description[i])){
                JOptionPane.showMessageDialog(null, "Task Description is too long, try again.");
            }else{
                continue;
            }
           }while(description[i].length()>50);
           
           //Prompt the user to enter task developer details
           developerDetails = new String[numTasks];
           developerDetails[i] = JOptionPane.showInputDialog("Enter Developer Details:");
           
           //Prompt the user to enter task duration in hours
           taskDuration = new int [numTasks];
           taskDuration[i] = Integer.parseInt(JOptionPane.showInputDialog("Enter Task Duration (in hours):"));
           
           //Task ID should be autogenerated
           taskID= new String[numTasks];
           taskID[i]=createTaskID(taskname[i] ,developerDetails[i],i);
           JOptionPane.showMessageDialog(null,"Task ID:" + taskID[i]);
           
           //Display and question message for the Task 
           taskStatus= new String[numTasks];
           taskStatus[i]= (String)JOptionPane.showInputDialog(null,"Select Task Status:","Task Status:",JOptionPane.QUESTION_MESSAGE,null,selection,selection[2]);
               
          // Printing the details of the captured tasks
            JOptionPane.showMessageDialog(null,"Tasks successfully captured:\n" + printTaskDetails(i));
               }
               
         
      }catch(NumberFormatException e){
          JOptionPane.showMessageDialog(null,"Please try again");
          return;
                  
      }
      }
       
      //method to display all of the tasks
      public String displayAllTasks() {
        StringBuilder report = new StringBuilder("All taskes are caputured:\n");
        for (int i = 0; i < taskname.length; i++) {
            report.append("\nTask Name: ").append(taskname[i])
                    .append("\nDeveloper: ").append(developerDetails[i])
                    .append("\nTask ID: ").append(taskID[i])
                    .append("\nTask Duration: ").append(taskDuration[i])
                    .append("\nTask Status: ").append(taskStatus[i]).append("\n");
        }
        return report.toString();
    }
    
   //method to display the for all tasks with the status of done
    public String displayStatusDone(String[] developerDetails,String[] taskname,int[] taskDuration){
        StringBuilder report=new StringBuilder("Tasks with status 'Done':\n");
        for (int i=0;i<taskStatus.length;i++){
            if (taskStatus[i].equalsIgnoreCase("Done")){
                report.append("Developer: ").append(developerDetails[i])
                       .append("Task Name: ").append(taskname[i])
                       .append("Task Duration: ").append(taskDuration[i]).append("\n");
            }
        }
        return report.toString();
    }
    
    //method to diaply the longest duration
    public String longestDuration(String[] developerDetails,String[] taskname,int[] taskDuration){
        if (taskDuration.length == 0) {
            return "No tasks accessible.";
        }

        int maxDurationIndex = 0;
        for (int i = 1; i < taskDuration.length; i++) {
            if (taskDuration[i] > taskDuration[maxDurationIndex]) {
                maxDurationIndex = i;
            }
        }
        return "Task with longest duration: \nDeveloper: "+ developerDetails[maxDurationIndex] +"\n Task Duration: " + taskDuration[maxDurationIndex];
    }
    
    //method to search task by name 
    public String searchTaskname(String[] taskname,String searchname){
        for(int i=0 ;i < taskname.length ;i++){
           if(taskname[i].equalsIgnoreCase(searchname)) {
               return "Task found\n Taskname: "+ taskname[i] + "\nDeveloper: " + developerDetails[i] +"Task Status: "+ taskStatus[i];
           }
        }
        return "Task not available";
    }
    
    //method to search for all tasks assigned to the developer
    public String searchTaskByDeveloper(String[] developerDetails,String searchDeveloper){
        StringBuilder report = new StringBuilder("Tasks assigned to " + developerDetails + ":\n");
        for (int i = 0; i < developerDetails.length; i++) {
            if (developerDetails[i].equalsIgnoreCase(searchDeveloper)) {
                report.append("Task Name: ").append(taskname[i]).append("\n Task Status: ").append(taskStatus[i]).append("\n");
            }
        }
    return report.toString();
    }
    
    //method to delete a task
    public String deleteTask(String[] taskname,String deleteTaskname){
           for (int i = 0; i < taskname.length; i++) {
            if (taskname[i].equalsIgnoreCase(deleteTaskname)) {
                for (int k = i; k < taskname.length - 1; k++) {
                    taskname[k] = taskname[k + 1];
                    developerDetails[k] = developerDetails[k + 1];
                    taskID[k] = taskID[k + 1];
                    taskDuration[k] = taskDuration[k + 1];
                    taskStatus[k] = taskStatus[k + 1];
                }
                i--;
                return "Task successfully deleted";
            }
        }
        return "Task not Deleted";
    }
      //method for the show report 
       public void showReport() {
        while (true) {
           int option = Integer.parseInt(JOptionPane.showInputDialog("""
                                                                     Choose a report option:
                                                                     1.Display All the task
                                                                     2.Display task with Done status
                                                                     3.Display longest duration of tasks
                                                                     4.Search task by name
                                                                     5.Search task by developer name
                                                                     6.Delete tasks
                                                                     7.back""")); 
        switch (option) {
               case 1:
            // displays all the tasks captured
            JOptionPane.showMessageDialog(null,displayAllTasks());
            break;
            
                case 2:
            // displays all the Done tasks
            JOptionPane.showMessageDialog(null, displayStatusDone(developerDetails,taskname,taskDuration));
            break;
            
                case 3:
            //display the longest duration of tasks
            JOptionPane.showMessageDialog(null,longestDuration(developerDetails,taskname,taskDuration));
            break;
            
                case 4:
            // Search task by task name 
                    
            String searchname = JOptionPane.showInputDialog("Enter task name to search:");
           searchTaskname(taskname,searchname);
           break;
            
                case 5:
            // search task by developer names 
            String serachDev=JOptionPane.showInputDialog("Enter developer name to search:");
            searchTaskByDeveloper(developerDetails,serachDev);
            break;

                case 6:
            // Enable user to delete the capured tasks
           String deleteTask= JOptionPane.showInputDialog("Enter task name to delete:");
           deleteTask(taskname,deleteTask);
           break;
            
            default:
              JOptionPane.showMessageDialog(null,"Invalid option");
              break;
                 }
            }
}
}
